# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/mahmoud/Downloads/clion-2020.1.2/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/mahmoud/Downloads/clion-2020.1.2/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mahmoud/Digital-Logic-Simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mahmoud/Digital-Logic-Simulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/mahmoud/Downloads/clion-2020.1.2/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/mahmoud/Downloads/clion-2020.1.2/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mahmoud/Digital-Logic-Simulator/CMakeFiles /home/mahmoud/Digital-Logic-Simulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mahmoud/Digital-Logic-Simulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Logic_Simulator

# Build rule for target.
Logic_Simulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Logic_Simulator
.PHONY : Logic_Simulator

# fast build rule for target.
Logic_Simulator/fast:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/build
.PHONY : Logic_Simulator/fast

src/AndGate.o: src/AndGate.cpp.o

.PHONY : src/AndGate.o

# target to build an object file
src/AndGate.cpp.o:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/AndGate.cpp.o
.PHONY : src/AndGate.cpp.o

src/AndGate.i: src/AndGate.cpp.i

.PHONY : src/AndGate.i

# target to preprocess a source file
src/AndGate.cpp.i:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/AndGate.cpp.i
.PHONY : src/AndGate.cpp.i

src/AndGate.s: src/AndGate.cpp.s

.PHONY : src/AndGate.s

# target to generate assembly for a file
src/AndGate.cpp.s:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/AndGate.cpp.s
.PHONY : src/AndGate.cpp.s

src/Gate.o: src/Gate.cpp.o

.PHONY : src/Gate.o

# target to build an object file
src/Gate.cpp.o:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/Gate.cpp.o
.PHONY : src/Gate.cpp.o

src/Gate.i: src/Gate.cpp.i

.PHONY : src/Gate.i

# target to preprocess a source file
src/Gate.cpp.i:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/Gate.cpp.i
.PHONY : src/Gate.cpp.i

src/Gate.s: src/Gate.cpp.s

.PHONY : src/Gate.s

# target to generate assembly for a file
src/Gate.cpp.s:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/Gate.cpp.s
.PHONY : src/Gate.cpp.s

src/GateFactory.o: src/GateFactory.cpp.o

.PHONY : src/GateFactory.o

# target to build an object file
src/GateFactory.cpp.o:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/GateFactory.cpp.o
.PHONY : src/GateFactory.cpp.o

src/GateFactory.i: src/GateFactory.cpp.i

.PHONY : src/GateFactory.i

# target to preprocess a source file
src/GateFactory.cpp.i:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/GateFactory.cpp.i
.PHONY : src/GateFactory.cpp.i

src/GateFactory.s: src/GateFactory.cpp.s

.PHONY : src/GateFactory.s

# target to generate assembly for a file
src/GateFactory.cpp.s:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/GateFactory.cpp.s
.PHONY : src/GateFactory.cpp.s

src/NANDGate.o: src/NANDGate.cpp.o

.PHONY : src/NANDGate.o

# target to build an object file
src/NANDGate.cpp.o:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/NANDGate.cpp.o
.PHONY : src/NANDGate.cpp.o

src/NANDGate.i: src/NANDGate.cpp.i

.PHONY : src/NANDGate.i

# target to preprocess a source file
src/NANDGate.cpp.i:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/NANDGate.cpp.i
.PHONY : src/NANDGate.cpp.i

src/NANDGate.s: src/NANDGate.cpp.s

.PHONY : src/NANDGate.s

# target to generate assembly for a file
src/NANDGate.cpp.s:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/NANDGate.cpp.s
.PHONY : src/NANDGate.cpp.s

src/NORGate.o: src/NORGate.cpp.o

.PHONY : src/NORGate.o

# target to build an object file
src/NORGate.cpp.o:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/NORGate.cpp.o
.PHONY : src/NORGate.cpp.o

src/NORGate.i: src/NORGate.cpp.i

.PHONY : src/NORGate.i

# target to preprocess a source file
src/NORGate.cpp.i:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/NORGate.cpp.i
.PHONY : src/NORGate.cpp.i

src/NORGate.s: src/NORGate.cpp.s

.PHONY : src/NORGate.s

# target to generate assembly for a file
src/NORGate.cpp.s:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/NORGate.cpp.s
.PHONY : src/NORGate.cpp.s

src/NOTGate.o: src/NOTGate.cpp.o

.PHONY : src/NOTGate.o

# target to build an object file
src/NOTGate.cpp.o:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/NOTGate.cpp.o
.PHONY : src/NOTGate.cpp.o

src/NOTGate.i: src/NOTGate.cpp.i

.PHONY : src/NOTGate.i

# target to preprocess a source file
src/NOTGate.cpp.i:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/NOTGate.cpp.i
.PHONY : src/NOTGate.cpp.i

src/NOTGate.s: src/NOTGate.cpp.s

.PHONY : src/NOTGate.s

# target to generate assembly for a file
src/NOTGate.cpp.s:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/NOTGate.cpp.s
.PHONY : src/NOTGate.cpp.s

src/Node.o: src/Node.cpp.o

.PHONY : src/Node.o

# target to build an object file
src/Node.cpp.o:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/Node.cpp.o
.PHONY : src/Node.cpp.o

src/Node.i: src/Node.cpp.i

.PHONY : src/Node.i

# target to preprocess a source file
src/Node.cpp.i:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/Node.cpp.i
.PHONY : src/Node.cpp.i

src/Node.s: src/Node.cpp.s

.PHONY : src/Node.s

# target to generate assembly for a file
src/Node.cpp.s:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/Node.cpp.s
.PHONY : src/Node.cpp.s

src/OrGate.o: src/OrGate.cpp.o

.PHONY : src/OrGate.o

# target to build an object file
src/OrGate.cpp.o:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/OrGate.cpp.o
.PHONY : src/OrGate.cpp.o

src/OrGate.i: src/OrGate.cpp.i

.PHONY : src/OrGate.i

# target to preprocess a source file
src/OrGate.cpp.i:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/OrGate.cpp.i
.PHONY : src/OrGate.cpp.i

src/OrGate.s: src/OrGate.cpp.s

.PHONY : src/OrGate.s

# target to generate assembly for a file
src/OrGate.cpp.s:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/OrGate.cpp.s
.PHONY : src/OrGate.cpp.s

src/Simulator.o: src/Simulator.cpp.o

.PHONY : src/Simulator.o

# target to build an object file
src/Simulator.cpp.o:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/Simulator.cpp.o
.PHONY : src/Simulator.cpp.o

src/Simulator.i: src/Simulator.cpp.i

.PHONY : src/Simulator.i

# target to preprocess a source file
src/Simulator.cpp.i:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/Simulator.cpp.i
.PHONY : src/Simulator.cpp.i

src/Simulator.s: src/Simulator.cpp.s

.PHONY : src/Simulator.s

# target to generate assembly for a file
src/Simulator.cpp.s:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/Simulator.cpp.s
.PHONY : src/Simulator.cpp.s

src/XNORGate.o: src/XNORGate.cpp.o

.PHONY : src/XNORGate.o

# target to build an object file
src/XNORGate.cpp.o:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/XNORGate.cpp.o
.PHONY : src/XNORGate.cpp.o

src/XNORGate.i: src/XNORGate.cpp.i

.PHONY : src/XNORGate.i

# target to preprocess a source file
src/XNORGate.cpp.i:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/XNORGate.cpp.i
.PHONY : src/XNORGate.cpp.i

src/XNORGate.s: src/XNORGate.cpp.s

.PHONY : src/XNORGate.s

# target to generate assembly for a file
src/XNORGate.cpp.s:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/XNORGate.cpp.s
.PHONY : src/XNORGate.cpp.s

src/XORGate.o: src/XORGate.cpp.o

.PHONY : src/XORGate.o

# target to build an object file
src/XORGate.cpp.o:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/XORGate.cpp.o
.PHONY : src/XORGate.cpp.o

src/XORGate.i: src/XORGate.cpp.i

.PHONY : src/XORGate.i

# target to preprocess a source file
src/XORGate.cpp.i:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/XORGate.cpp.i
.PHONY : src/XORGate.cpp.i

src/XORGate.s: src/XORGate.cpp.s

.PHONY : src/XORGate.s

# target to generate assembly for a file
src/XORGate.cpp.s:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/XORGate.cpp.s
.PHONY : src/XORGate.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Logic_Simulator.dir/build.make CMakeFiles/Logic_Simulator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Logic_Simulator"
	@echo "... src/AndGate.o"
	@echo "... src/AndGate.i"
	@echo "... src/AndGate.s"
	@echo "... src/Gate.o"
	@echo "... src/Gate.i"
	@echo "... src/Gate.s"
	@echo "... src/GateFactory.o"
	@echo "... src/GateFactory.i"
	@echo "... src/GateFactory.s"
	@echo "... src/NANDGate.o"
	@echo "... src/NANDGate.i"
	@echo "... src/NANDGate.s"
	@echo "... src/NORGate.o"
	@echo "... src/NORGate.i"
	@echo "... src/NORGate.s"
	@echo "... src/NOTGate.o"
	@echo "... src/NOTGate.i"
	@echo "... src/NOTGate.s"
	@echo "... src/Node.o"
	@echo "... src/Node.i"
	@echo "... src/Node.s"
	@echo "... src/OrGate.o"
	@echo "... src/OrGate.i"
	@echo "... src/OrGate.s"
	@echo "... src/Simulator.o"
	@echo "... src/Simulator.i"
	@echo "... src/Simulator.s"
	@echo "... src/XNORGate.o"
	@echo "... src/XNORGate.i"
	@echo "... src/XNORGate.s"
	@echo "... src/XORGate.o"
	@echo "... src/XORGate.i"
	@echo "... src/XORGate.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

